services:
  dnt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    entrypoint: ["dumb-init", "--"]
    environment:
      - DNT_VERBOSE
